---
- hosts: localhost
  roles:
    - role: bradfordwagner.go-releaser-install
      vars:
        gri_installs:
          - repo: bradfordwagner/go-cli-buildkit-ch
            binary_name: bkch
            tag: 0.2.1
  tasks:
    - name: check binaries installed
      include_tasks: ./tests/check_output.yml
      loop_control:
        loop_var: item
      loop:
        - /usr/local/bin/bkch -h
    - name: Address CVEs
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: absent
      loop:
        - path: /ansible_env
